LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := bootctrl.trinket
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_SUFFIX := .a
LOCAL_SRC_FILES := bootctrl/dummy.c
LOCAL_VENDOR_MODULE := true
include $(BUILD_STATIC_LIBRARY)